version: '3.8'
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: sredemo-springboot
    networks:
      - sredemo
    ports: 
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_IP}:3306/sredemo
      SPRING_DATASOURCE_USERNAME: "${DB_USER:-root}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD:-root}"
    restart: unless-stopped